connector.name=postgresql
connection-url=jdbc:postgresql://${ENV:PHOENIX_DB_HOST}:${ENV:PHOENIX_DB_PORT}/${ENV:PHOENIX_DB_NAME}
connection-user=${ENV:PHOENIX_DB_USER}
connection-password=${ENV:PHOENIX_DB_PASSWORD}